name: Mon Premier Robot

on: [push]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    
    steps:
    - name: Dire Bonjour
      run: echo "👋 Bonjour ! Votre code vient d'arriver !"
      
    - name: Montrer les fichiers
      run: ls -la